apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1  
    kind: Deployment
    name: deploy
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50