apiVersion: apps/v1
kind: Deployment 
metadata:
  name: tennis-api 
  namespace: dipdevopsgrupo5 
  labels:
    app: tennis-api 
spec:
  revisionHistoryLimit: 2 
  strategy:
    type: RollingUpdate 
  replicas: 2 
  selector:
    matchLabels:
      app: tennis-api 
  template: 
    metadata:
      labels: 
        app: tennis-api
    spec:
      volumes:
        - name: 'empty'
          emptyDir: {}
        - name: grupo5
          configMap:
            name: grupo5
      containers:
      - name: tennis-api 
        image: ualmtorres/tennis-api:v0 
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
